### PR TITLE
Fix to dataframe interpolation

### PR DESCRIPTION
**Pull request by melund**
This fixes a bug in the `to_dataframe()` function which prevented interpolation from working. It also adds a test so the bug doesn't come back.

Finally, it update the version to prepare for a 1.8.2 release. 

fixes: #95

### CODE REVIEW

**Comment by melund** [comment]
@depierie / @marcbandi I have added a pull request with your fix to the interpolation bug. 

Thanks a ton for this..

**Comment by melund** [comment]
I will cut a new release once this gets merged.

**Review by depierie — APPROVED** [review]
Tested successfully

**Review by depierie — APPROVED** [review]
Tested successfully

**Comment by depierie** [comment]
Tested successfully

**Review by depierie — APPROVED** [review]

**Comment by melund** [comment]
Thanks Enrico. I think the system thought it needed an extra inside reviewer. But that is not a problem. I can still merge it.

**Comment by melund** [comment]
I will make a new release now, and new conda-packages should be up automatically by tomorrow.

**Pull request merged**
